config/routes.rb
Sociable::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destory]
  resources :posts, :only => [:create, :destroy]
  resources :pairs, :only => [:create, :edit, :update, :destroy] do
    put :accept, :on => :member
  end

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  root :to => 'pages#home'

end

app/views/shared/_accept_pair.html.erb
<%= form_for pair_request, :url => accept_pair_path(pair_request) do |f| %>
  <div>
    <%= f.hidden_field :user_id, :value => pair_request.user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Accept" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
    <p> The following fields had problems </p>
    <ul>
    <% object.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="posts" summary="user post feed">
    <%= paginate @feed_items %>
    <%= render :partial => "shared/feed_item", :collection => @feed_items %>
  </table>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </td>
  <td class="content">
    <%= feed_item.content %>
  </td>
  <td class="timestamp">
    cleverly stated <%= time_ago_in_words(feed_item.created_at) %> ago.
  </td>
  <% if current_user == feed_item.user %>
    <td>
      <%= link_to 'delete', feed_item, 
              :method => "delete",
              :confirm => "but your words were so pretty",
              :title => feed_item.content %>
    </td>
  <% end %>
</tr>

app/views/shared/_pair_request.html.erb
<li>
  <span class="user">
    <%= link_to pair_request.user.name, pair_request.user %>
  </span>
  <br />
  <span class="accept">
    <%= render :partial => 'shared/accept_pair', :locals => {:pair_request => pair_request} %>
  </span>
  <span class="reject">
    <%= render :partial => 'shared/reject_pair', :locals => {:pair_request => pair_request} %>
  </span>
</li>

app/views/shared/_pair_requests.html.erb
<% unless @pair_requests.empty? %>
  <section id="wing-requests">
    <h1>New Wing Requests</h1>
    <ul class="wing-requests" summary="wing requests">
      <%= render :partial => "shared/pair_request", :collection => @pair_requests %>
    </ul>
  </section>
<% end %>

app/views/shared/_post_form.html.erb
<section class="post">
<h1>Shout to the heavens (or the rest of the testers)</h1>
<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>
</section>

app/views/shared/_reject_pair.html.erb
<%= link_to "Reject", pair_request, :method => :delete %>

app/views/shared/_sidebar.html.erb
<section id="sidebar">
  <p> number of wings: <%= current_user.wings.count %> </p>
  <% unless current_user.wings.nil? %>
  <ul>
    <% current_user.wings.each do |wing| %>
      <li> <%= link_to wing.name, wing %> </li>
    <% end %>
  </ul>
  <% end %>
</section>

app/views/shared/_wing_requests.html.erb
<% unless @pair_requests.empty? %>
  <section id="wing-requests">
    <h1>New Wing Requests</h1>
    <ul class="wing-requests" summary="wing requests">
      <%= render :partial => "shared/pair_request", :collection => @pair_requests %>
    </ul>
  </section>
<% end %>