config/routes.rb
Sociable::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destory]
  resources :posts, :only => [:create, :destroy]
  resources :pairs, :only => [:create, :edit, :update, :destroy] do
    put :accept, :on => :member
  end

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  root :to => 'pages#home'

end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Edit", edit_user_path(current_user) %></li>
      <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
  <hgroup>
    <h1><%= link_to "Ride Sociable", root_path %> </h1>
    <h2><%= tagline %></h2>
  </hgroup>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'application' %>
  <script type="text/javascript" src="http://use.typekit.com/ymx3omt.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= render :partial => 'layouts/flash', :locals => {:flash => flash} %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>